# TB Drug Resistance Exploratory Data Analysis

The system rests on two datasets. The first is a synthetic patient case base that supports case-based reasoning. The second is the CRyPTIC cohort of real isolates that supports resistance classification. This notebook gives an overview of both.

## Synthetic case base

This first part covers four things. It measures the outcome signal in each feature, which sets the similarity weights. It checks the class imbalance across the six resistance profiles, which drives retrieval coverage. It fixes the trivial baselines a case-based design must beat, namely always predicting success for the outcome and the modal regimen per profile. It also reviews the seed graph coverage and its gaps.

In [1]:
import ast
import random
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

# The notebook runs from EDA/. Source modules sit in the sibling SRC/ and
# Evaluation/ folders, and the CRyPTIC tables in Datasets/.
ROOT = Path.cwd().parent
DATA = ROOT / "Datasets"
sys.path[:0] = [str(ROOT / "SRC"), str(ROOT / "Evaluation")]

from cbr_cases import case_base, regimen_ceiling
from feature_engineering import SEVERITY
from validation import (
    K_FOLDS,
    N_CASES,
    RESISTANT_TIERS,
    SEED,
    baseline_accuracy,
    stratified_folds,
)

cases = case_base(N_CASES, SEED)
frame = pd.DataFrame(cases)
success = frame["outcome"].eq("success")
len(frame)

1000

## 1. Distribution sanity check
Proportions across the whole case base, computed independently of `CaseGenerator.distribution_summary`, act as a cross-check that the generation matches the targets.

In [2]:
pd.concat({
    "profile": frame["profile"].value_counts(normalize=True).round(3),
    "region": frame["region"].value_counts(normalize=True).round(3),
})

profile  Susceptible        0.500
         MDR                0.180
         MonoResistant      0.120
         PreXDR             0.080
         XDR                0.060
         PolyResistant      0.060
region   SE_Asia            0.292
         African            0.254
         W_Pacific          0.147
         European           0.112
         E_Mediterranean    0.105
         Americas           0.090
Name: proportion, dtype: float64

In [3]:
frame["outcome"].value_counts(normalize=True).round(3)

outcome
success          0.746
death            0.102
ltfu             0.080
failed           0.044
not_evaluated    0.028
Name: proportion, dtype: float64

In [4]:
pd.Series({
    "hiv_positive": frame["hiv_status"].eq("positive").mean(),
    "diabetes": frame["diabetes"].mean(),
    "previous_treatment": frame["previous_treatment"].mean(),
    "mean_age": frame["age"].mean(),
}).round(3)

hiv_positive           0.112
diabetes               0.189
previous_treatment     0.161
mean_age              39.991
dtype: float64

## 2. Class balance across the six resistance profiles
Counts, share, and success rate for each profile, ordered by clinical severity. The case base is mostly Susceptible, and the resistant categories (PolyResistant, PreXDR, XDR) are much smaller. That shapes a clear design point. Neighbor-based retrieval has abundant data for Susceptible cases and thin data for the rarer resistant classes, so data quality per profile varies rather than holding steady.

In [5]:
pd.DataFrame({
    "n": frame["profile"].value_counts(),
    "share": frame["profile"].value_counts(normalize=True).round(3),
    "success_rate": success.groupby(frame["profile"]).mean().round(3),
}).reindex(SEVERITY)

,n,share,success_rate
profile,,,
Susceptible,500,0.50,0.820
MonoResistant,120,0.12,0.783
PolyResistant,60,0.06,0.717
MDR,180,0.18,0.694
PreXDR,80,0.08,0.650
XDR,60,0.06,0.367


## 3. Outcome signal by feature
Success rate varies across the values of each candidate similarity feature. A feature with a wide success-rate spread carries outcome signal and earns a higher weight in the similarity metric, while a feature with little spread earns less. This grounds the weights in the data rather than in assumptions. Region is included on purpose. It shapes prevalence and demographics in the generator but does not act on the outcome directly, so a nearly flat region row points to a low weight.

In [6]:
AGE_BINS = [17, 34, 49, 64, 80]
frame["age_band"] = pd.cut(frame["age"], bins=AGE_BINS,
                           labels=[f"{lo + 1}-{hi}"
                                   for lo, hi in zip(AGE_BINS, AGE_BINS[1:], strict=False)])


def outcome_signal(column):
    return success.groupby(frame[column], observed=True).mean().round(3)


features = ["hiv_status", "previous_treatment", "diabetes", "sex", "age_band", "region"]
pd.concat({c: outcome_signal(c) for c in features})

hiv_status          negative           0.747
                    positive           0.741
previous_treatment  False              0.768
                    True               0.634
diabetes            False              0.760
                    True               0.688
sex                 F                  0.758
                    M                  0.740
age_band            18-34              0.769
                    35-49              0.760
                    50-64              0.703
                    65-80              0.635
region              African            0.752
                    Americas           0.811
                    E_Mediterranean    0.724
                    European           0.741
                    SE_Asia            0.733
                    W_Pacific          0.741
Name: outcome, dtype: float64

## 4. Trivial baselines to beat
Two simple predictors set the floor a case-based design must clear. The first always predicts success for the outcome. The second predicts the most frequent regimen within each resistance profile.

Only the second predictor has anything to fit. Its lookup table of one regimen per profile is estimated from the cases it sees, so scoring it on those same cases reports a resubstitution figure rather than a floor. The case-based engine is scored out of fold, so the baseline is fit on the training portion of each fold and scored on the held-out portion. Both then face the same comparison. The fold splits and the scoring come from `validation.py`, so the figures here and the ones in the validation report are produced by the same code rather than by two similar versions of it.

The table below reports the held-out mean and standard deviation next to the resubstitution figure, so the size of the difference is visible rather than assumed. The per-profile tables that follow give the context behind each headline number. Where a single regimen holds an entire profile, the prediction is correct by construction. Where the regimens divide across two or three options, a retrieval model has room to add value.

In [7]:
folds = stratified_folds(cases, K_FOLDS, random.Random(SEED))
held_out = pd.DataFrame([baseline_accuracy(train, test) for train, test in folds])

pd.DataFrame({
    "held_out_mean": held_out.mean().round(3),
    "held_out_std": held_out.std().round(3),
    "resubstitution": pd.Series(baseline_accuracy(cases, cases)),
})

,held_out_mean,held_out_std,resubstitution
outcome,0.746,0.031,0.746
regimen,0.785,0.015,0.797


A baseline says what a method must beat. A ceiling says what any method could
reach. The generator draws the regimen from the profile and the year alone, so no
predictor reading a case can do better than the share held by the most common
option within each of those groups. The two figures below bound the useful range
from each side, and the validation run reports the same ceiling next to its own
accuracy. When the baseline sits close to the ceiling the task is saturated, and
a score between them says more about the generator than about the method.

In [8]:
regimen_baseline = held_out.mean()["regimen"]
ceiling = regimen_ceiling()

pd.Series({
    "regimen_baseline": round(float(regimen_baseline), 3),
    "regimen_ceiling": ceiling,
    "headroom": round(float(ceiling - regimen_baseline), 3),
})

regimen_baseline    0.785
regimen_ceiling     0.807
headroom            0.022
dtype: float64

In [9]:
outcome_baseline = pd.Series({
    "overall": success.mean(),
    **success.groupby(frame["profile"]).mean().to_dict(),
}).round(3)
outcome_baseline.reindex(["overall", *SEVERITY])

overall          0.746
Susceptible      0.820
MonoResistant    0.783
PolyResistant    0.717
MDR              0.694
PreXDR           0.650
XDR              0.367
dtype: float64

In [10]:
shares = (frame.groupby("profile")["regimen"].value_counts(normalize=True)
          .rename("share").reset_index())
modal = shares.sort_values("share", ascending=False).drop_duplicates("profile")

pd.DataFrame({
    "modal_regimen": modal.set_index("profile")["regimen"],
    "majority_share": modal.set_index("profile")["share"].round(3),
    "n_regimens": shares.groupby("profile")["regimen"].size(),
}).reindex(SEVERITY)

,modal_regimen,majority_share,n_regimens
profile,,,
Susceptible,2HRZE_4HR,1.000,1
MonoResistant,6REZ_Lfx,1.000,1
PolyResistant,AllOral_9mo,0.517,2
MDR,BPaLM,0.450,3
PreXDR,BPaL,0.512,2
XDR,BPaL,0.400,3


## 5. Seed knowledge-graph composition
A static overview of the hand-curated strains in `tb_ontology.py`, read from the same source blob the test suite parses. This keeps the overview database-free and aligned with `test_core`. It shows what the curated graph holds (profiles, genes, and geography) and, just as important, what it leaves out. Those gaps are real. A query for an absent combination should return no rows rather than a fabricated strain. The integrity of the profile against mutation relationships is checked in the test suite, not re-proven here, since this section is for exploration rather than validation.

In [11]:
BLOB_NAMES = ("strains", "strain_data", "mutations")

tree = ast.parse((ROOT / "SRC" / "tb_ontology.py").read_text())
blobs = {target.id: ast.literal_eval(node.value)
         for node in tree.body if isinstance(node, ast.Assign)
         for target in node.targets
         if isinstance(target, ast.Name) and target.id in BLOB_NAMES}

country = {s["id"]: s["country"] for s in blobs["strains"]}
gene = {m["id"]: m["gene"] for m in blobs["mutations"]}

kg = pd.DataFrame([{
    "strain": r["strain"],
    "country": country.get(r["strain"]),
    "profile": r["profile"],
    "genes": sorted({gene.get(m) for m in r["mutations"]} - {None}),
} for r in blobs["strain_data"]])

kg["profile"].value_counts().reindex(SEVERITY)

profile
Susceptible       6
MonoResistant    22
PolyResistant     9
MDR              10
PreXDR            7
XDR               2
Name: count, dtype: int64

In [12]:
pd.Series({
    "strains": len(kg),
    "countries": kg["country"].nunique(),
    "distinct_genes": len({g for genes in kg["genes"] for g in genes}),
})

strains           56
countries         42
distinct_genes     8
dtype: int64

In [13]:
india = kg[kg["country"] == "India"]
india[["strain", "profile", "genes"]]

,strain,profile,genes
3,TB004,PolyResistant,"[embB, inhA]"
4,TB005,MonoResistant,"[inhA, katG]"
33,TB034,PolyResistant,"[inhA, pncA]"
51,TB052,Susceptible,[]


The sections above run on the synthetic case base alone and need no datasets. The sections below read the CRyPTIC and WHO data files described in DEPLOYME.md, so they need those files present to run.

## 6. CRyPTIC real-world isolates

The remaining sections describe the CRyPTIC Release 3.4.0 cohort. These are real *M. tuberculosis* isolates with whole-genome variants graded against the WHO 2023 mutation catalog and measured drug-susceptibility phenotypes. The cohort carries genotype and phenotype only, with no treatment outcomes.

In [14]:
from feature_engineering import drug_map, flat, resistant_profile

# Reuse the CRyPTIC profile derivation so this notebook and the model-ready
# table cannot drift.
drugs = drug_map(DATA / "DRUG_CODES.csv")

## 7. Data sources and scale
The analysis draws on five tables. EFFECTS grades each isolate's mutations against the WHO 2023 catalog as R, S, U, or F. PREDICTIONS gives the catalog's per-drug genotypic call. DST_MEASUREMENTS and UKMYC_PHENOTYPES hold the measured susceptibility. DRUG_CODES maps the three-letter drug codes to drug names. The genome-wide MUTATIONS table is left out because EFFECTS already provides the same variants in graded form. The counts below cover the four parquet tables.

In [15]:
files = ["EFFECTS.parquet", "PREDICTIONS.parquet",
         "DST_MEASUREMENTS.parquet", "UKMYC_PHENOTYPES.parquet"]
pd.Series({name: pq.ParquetFile(DATA / name).metadata.num_rows for name in files})

EFFECTS.parquet             1154127
PREDICTIONS.parquet          810615
DST_MEASUREMENTS.parquet     660961
UKMYC_PHENOTYPES.parquet     288904
dtype: int64

## 8. Measured resistance-profile balance
Resistance profile derived from the DST measured phenotypes using the system's class definitions. As a resistance-prediction cohort, CRyPTIC holds thousands of isolates in every resistant tier, including pre-XDR and XDR. That distribution differs sharply from population prevalence, where those tiers would be sparse. PolyResistant is the smallest class and the narrowest by definition.

In [16]:
dst = resistant_profile(DATA / "DST_MEASUREMENTS.parquet", "PHENOTYPE", drugs)
dst.value_counts().reindex(SEVERITY)

Susceptible      35661
MonoResistant     7762
PolyResistant     4642
MDR              10335
PreXDR            4725
XDR               2463
Name: count, dtype: int64

## 9. Cross-assay label concordance
UKMYC is an independent MIC-based assay. Across the isolates measured by both methods, the derived profiles are compared. Concordance is high, and every disagreement runs the same way, with UKMYC placing the isolate in a less severe tier than DST. The cells that follow decompose that pattern, because a difference that is entirely one-directional means something other than symmetric measurement noise and needs a different explanation.

In [17]:
ukmyc = resistant_profile(DATA / "UKMYC_PHENOTYPES.parquet", "BINARY_PHENOTYPE", drugs)
both = pd.DataFrame({"dst": dst, "ukmyc": ukmyc}).dropna()
pd.Series({"measured_by_both": len(both),
           "agreement": round((both["dst"] == both["ukmyc"]).mean(), 3)})

measured_by_both    21568.000
agreement               0.948
dtype: float64

In [18]:
both[both["dst"] != both["ukmyc"]]["dst"].value_counts().reindex(SEVERITY, fill_value=0)

dst
Susceptible        0
MonoResistant    198
PolyResistant    182
MDR              347
PreXDR           192
XDR              198
Name: count, dtype: int64

Grouping the disagreements by the DST tier alone cannot show which assay called less resistance. The table below crosses the two, with the DST tier down the rows and the UKMYC tier across the columns. Entries to the left of the diagonal are isolates UKMYC placed in a less severe tier than DST, and entries to the right are the reverse. A count that sits almost entirely on one side means the assays differ in a fixed direction rather than disagreeing at random, which is a stronger claim than a bare concordance rate can support.

In [19]:
disagree = both[both["dst"] != both["ukmyc"]]
rank = {profile: i for i, profile in enumerate(SEVERITY)}
lower = int((disagree["ukmyc"].map(rank) < disagree["dst"].map(rank)).sum())
print(f"disagreements {len(disagree)}, ukmyc lower {lower}, ukmyc higher {len(disagree) - lower}")

pd.crosstab(disagree["dst"], disagree["ukmyc"]).reindex(
    index=SEVERITY, columns=SEVERITY, fill_value=0)

disagreements 1117, ukmyc lower 1117, ukmyc higher 0


ukmyc,Susceptible,MonoResistant,PolyResistant,MDR,PreXDR,XDR
dst,,,,,,
Susceptible,0,0,0,0,0,0
MonoResistant,198,0,0,0,0,0
PolyResistant,25,157,0,0,0,0
MDR,42,116,189,0,0,0
PreXDR,6,27,42,117,0,0
XDR,7,34,49,11,97,0


The direction is total rather than merely skewed, so the two assays differ systematically instead of disagreeing at random. Two explanations fit. Either UKMYC is more conservative whenever it calls resistance, or it measures fewer drugs per isolate, in which case an isolate resistant to a drug UKMYC never tested appears less resistant through absence rather than through disagreement. The counts below separate the two, since a large gap in drugs measured per isolate points at coverage.

In [20]:
def measured_drugs(path, column):
    df = flat(pd.read_parquet(path, columns=["UNIQUEID", "DRUG", column]), "UNIQUEID")
    calls = df[df[column].astype(str).isin(["R", "S"])]
    return calls.groupby("UNIQUEID")["DRUG"].nunique()


coverage = pd.DataFrame({
    "dst": measured_drugs(DATA / "DST_MEASUREMENTS.parquet", "PHENOTYPE"),
    "ukmyc": measured_drugs(DATA / "UKMYC_PHENOTYPES.parquet", "BINARY_PHENOTYPE"),
}).dropna()
coverage.agg(["median", "mean", "min", "max"]).round(2)

,dst,ukmyc
median,13.00,13.00
mean,13.93,12.93
min,2.00,2.00
max,19.00,13.00


The panels match in the middle but not at the top. Both assays measure thirteen drugs for the median isolate, yet UKMYC never exceeds thirteen while DST reaches nineteen, so DST can call resistance on drugs the UKMYC plate does not carry. Panel size alone settles nothing, because two panels of equal size need not hold the same drugs.

The test below takes every resistance DST recorded in a disagreeing isolate and splits it three ways. UKMYC may have run the same drug and agreed, run it and called the isolate susceptible, or never run it at all. Only the middle group is a real difference of opinion. The first group is agreement that a coarser profile comparison hides, and the last is coverage rather than contradiction.

In [21]:
def drug_calls(path, column):
    """Isolate and drug pairs carrying an R or S call, with drug names normalized."""
    df = flat(pd.read_parquet(path, columns=["UNIQUEID", "DRUG", column]), "UNIQUEID")
    calls = df[df[column].astype(str).isin(["R", "S"])].copy()
    calls["drug"] = calls["DRUG"].astype(str).map(drugs)
    calls["resistant"] = calls[column].astype(str) == "R"
    return calls.dropna(subset=["drug"])[["UNIQUEID", "drug", "resistant"]]


dst_calls = drug_calls(DATA / "DST_MEASUREMENTS.parquet", "PHENOTYPE")
ukmyc_calls = drug_calls(DATA / "UKMYC_PHENOTYPES.parquet", "BINARY_PHENOTYPE")

dst_r = dst_calls[dst_calls["resistant"] & dst_calls["UNIQUEID"].isin(disagree.index)]
ukmyc_pairs = ukmyc_calls.groupby(["UNIQUEID", "drug"], as_index=False)["resistant"].max()
checked = dst_r.merge(ukmyc_pairs.rename(columns={"resistant": "ukmyc"}),
                      on=["UNIQUEID", "drug"], how="left")

ukmyc_call = checked["ukmyc"]

pd.Series({
    "dst_resistance_calls": len(checked),
    "ukmyc_agreed_resistant": int(ukmyc_call.eq(True).sum()),
    "ukmyc_called_susceptible": int(ukmyc_call.eq(False).sum()),
    "ukmyc_never_tested_it": int(ukmyc_call.isna().sum()),
})

dst_resistance_calls        6110
ukmyc_agreed_resistant      3302
ukmyc_called_susceptible    1366
ukmyc_never_tested_it       1442
dtype: int64

### Repeated calls for one isolate and drug

An isolate can carry more than one recorded call for the same drug. Both the
label builder and the per-drug scoring collapse those repeats to resistant, which
is a decision rather than a formality, so the count below shows how often it
binds. Reading the pairs from the table built above means this measures the same
rows the scoring sees.

In [22]:
spread = dst_calls.groupby(["UNIQUEID", "drug"])["resistant"].nunique()
conflicting = spread > 1

pd.Series({
    "isolate_drug_pairs": len(spread),
    "pairs_carrying_both_calls": int(conflicting.sum()),
    "share": round(float(conflicting.mean()), 4) if len(spread) else 0.0,
    "isolates_affected": spread[conflicting].index.get_level_values("UNIQUEID").nunique(),
})

isolate_drug_pairs           564708.0000
pairs_carrying_both_calls      3560.0000
share                             0.0063
isolates_affected              2527.0000
dtype: float64

## 10. Resistance signal versus phylogenetic background
Non-synonymous variants in resistance genes are not always tied to resistance. Several common changes (gyrA E21Q, gyrA S95T, katG R463L) act as phylogenetic markers and appear in most isolates. The true resistance determinants surface once the focus narrows to the catalog's resistance-graded calls. The ranking below, built from graded variants, brings the well-known resistance mutations to the top, such as katG S315T, rpoB S450L, and embB M306V.

In [23]:
def resistance_mutations(path):
    eff = flat(pd.read_parquet(path, columns=["UNIQUEID", "GENE", "MUTATION", "PREDICTION"]), "GENE")
    r = eff[eff["PREDICTION"].astype(str) == "R"]
    gene = r["GENE"].astype("string").fillna("NA")
    mut = gene.str.cat(r["MUTATION"].astype("string").fillna("NA"), sep="_")
    return r.assign(mut=mut).drop_duplicates(["UNIQUEID", "mut"])


resistance = resistance_mutations(DATA / "EFFECTS.parquet")
resistance["mut"].value_counts().head(15)

mut
katG_S315T     17071
rpoB_S450L     12359
rpsL_K43R       8843
embB_M306V      5155
fabG1_c-15t     4833
embB_M306I      3739
gyrA_D94G       2823
rrs_a1401g      2519
rrs_a514c       1652
gyrA_A90V       1643
rpoB_D435V      1564
rpsL_K88R       1451
embB_Q497R      1400
eis_c-12t        784
rrs_c517t        751
Name: count, dtype: Int64

## 11. Genotypic catalog prediction versus measured phenotype
The genotype-based profile from the catalog is compared with the measured phenotype profile, both overall and by category. Agreement is strongest for the Susceptible and high-resistance tiers and weakest for PolyResistant and MonoResistant, which rest on a small number of borderline calls.

In [24]:
catalog = resistant_profile(DATA / "PREDICTIONS.parquet", "PREDICTION", drugs)
compare = pd.DataFrame({"measured": dst, "catalog": catalog}).dropna()
compare["correct"] = compare["measured"] == compare["catalog"]
pd.Series({"n": len(compare), "exact_agreement": round(compare["correct"].mean(), 3)})

n                  53735.000
exact_agreement        0.736
dtype: float64

In [25]:
compare.groupby("measured")["correct"].mean().reindex(SEVERITY).round(3)

measured
Susceptible      0.868
MonoResistant    0.281
PolyResistant    0.376
MDR              0.743
PreXDR           0.748
XDR              0.785
Name: correct, dtype: float64

## 12. Catalog coverage gap between PREDICTIONS and EFFECTS
The rule engine reads graded mutations from EFFECTS, so an isolate with no EFFECTS rows reaches the engine with an empty genotype and is scored below-MDR. A few isolates carry a catalog call in PREDICTIONS yet have no graded rows in EFFECTS, and those isolates form the coverage gap. The counts below measure the gap across the full cohort and, within it, the isolates the catalog still calls resistant.

This gap is a property of the data, not a count of engine mistakes. The classification validation scores the full labeled cohort, where the same missing-input defect surfaces as the engine-only errors. The coverage gap counts every isolate that reaches the engine without graded rows, while the engine-only errors count only the subset where that missing input changes the predicted tier, so the gap is the larger figure and the two should be read separately rather than as the same number.

In [26]:
graded = set(flat(pd.read_parquet(DATA / "EFFECTS.parquet", columns=["UNIQUEID"]),
                  "UNIQUEID")["UNIQUEID"].unique())
predictions = flat(pd.read_parquet(DATA / "PREDICTIONS.parquet",
                                   columns=["UNIQUEID", "PREDICTION"]), "UNIQUEID")

gap = predictions[~predictions["UNIQUEID"].isin(graded)]
gap_ids = gap["UNIQUEID"].unique()
resistance_call = gap.loc[gap["PREDICTION"].astype(str) == "R", "UNIQUEID"].nunique()

pd.Series({
    "graded_in_effects": len(graded),
    "predicted_in_catalog": predictions["UNIQUEID"].nunique(),
    "coverage_gap": len(gap_ids),
    "gap_with_resistance_call": resistance_call,
})

graded_in_effects           53864
predicted_in_catalog        54041
coverage_gap                  200
gap_with_resistance_call      117
dtype: int64

The catalog tier of the gap isolates shows what the engine missed for want of input rows. The breakdown spans all gap isolates, and any MDR, PreXDR, or XDR call is a resistant isolate the rule engine scored below-MDR because EFFECTS held no graded mutation for it. The resistant tiers sum to fewer isolates than the resistance-call count above, since a handful of isolates carry an R call on a drug that does not drive the profile and so resolve to Susceptible here.

In [27]:
catalog.reindex(gap_ids).dropna().value_counts().reindex(SEVERITY, fill_value=0)

Susceptible      83
MonoResistant    10
PolyResistant    10
MDR              45
PreXDR           27
XDR              25
Name: count, dtype: int64

### The ceiling coverage puts on sensitivity

The gap measured above compares the two catalog tables to each other. The figure
that bounds the engine is a different one, because the engine is scored against
the measured phenotype and is handed only the rows EFFECTS grades as resistant.
An isolate with no such row arrives with an empty genotype and is called below
the multidrug-resistant tier whatever its phenotype, so it cannot be recovered by
any rule. The table below counts, for each resistant tier, how many isolates the
engine can reach at all. Every sensitivity figure reported elsewhere should be
read next to the ceiling on its own row rather than against one hundred percent.

In [28]:
effects = flat(pd.read_parquet(DATA / "EFFECTS.parquet", columns=["UNIQUEID", "PREDICTION"]),
               "UNIQUEID")
graded_r = set(effects.loc[effects["PREDICTION"].astype(str) == "R", "UNIQUEID"].unique())

resistant = dst[dst.isin(RESISTANT_TIERS)]
reachable = pd.Series(resistant.index.isin(graded_r), index=resistant.index)

ceiling = pd.DataFrame({
    "isolates": resistant.value_counts(),
    "reachable": reachable.groupby(resistant).sum(),
})
ceiling.loc["all tiers"] = ceiling.sum()
ceiling["unreachable"] = ceiling["isolates"] - ceiling["reachable"]
ceiling["ceiling"] = (ceiling["reachable"] / ceiling["isolates"].where(ceiling["isolates"] > 0)).round(3)
ceiling.reindex([*RESISTANT_TIERS, "all tiers"])

,isolates,reachable,unreachable,ceiling
MDR,10335,8445,1890,0.817
PreXDR,4725,3832,893,0.811
XDR,2463,1684,779,0.684
all tiers,17523,13961,3562,0.797


### Does the tier explain the gap, or does the cohort

The ceiling falls from 81.7 percent at MDR to 68.4 at XDR. Read alone that
invites the conclusion that the most resistant isolates are the hardest to
genotype, which would be a claim about resistance. Provenance is the competing
explanation, since the release pools several collections and they need not have
sequenced to the same depth.

The two are separated by measuring the same gap inside each source. If resistance
drives it the gap appears everywhere, and if one collection drives it the gap sits
in that collection and the rest sit near zero. Only isolates whose rows agree on a
single source are used, because the column varies within an isolate and a
disagreeing isolate has no source to group it under. Sources are shown only where
both tiers carry enough isolates to compare.

In [29]:
MIN_PER_TIER = 30

assert "SOURCE" in pq.ParquetFile(DATA / "DST_MEASUREMENTS.parquet").schema_arrow.names

raw = flat(pd.read_parquet(DATA / "DST_MEASUREMENTS.parquet",
                           columns=["UNIQUEID", "SOURCE"]), "UNIQUEID")

# One source per isolate, or none. Reducing a disagreeing isolate to one of its
# values would invent provenance the table does not carry.
agreed = raw.groupby("UNIQUEID")["SOURCE"].nunique(dropna=False).eq(1)
source = raw[raw["UNIQUEID"].isin(agreed[agreed].index)].groupby("UNIQUEID")["SOURCE"].first()

by_source = pd.DataFrame({"tier": resistant, "reachable": reachable}).join(source, how="inner")
pair = by_source[by_source["tier"].isin(("MDR", "XDR"))]
stats = pair.groupby(["SOURCE", "tier"], observed=True)["reachable"].agg(["mean", "size"]).unstack("tier")

gaps = pd.DataFrame({
    "mdr_coverage": stats[("mean", "MDR")].round(3),
    "xdr_coverage": stats[("mean", "XDR")].round(3),
    "n_mdr": stats[("size", "MDR")],
    "n_xdr": stats[("size", "XDR")],
})[(stats["size"] >= MIN_PER_TIER).all(axis=1)]
gaps["gap"] = (gaps["mdr_coverage"] - gaps["xdr_coverage"]).round(3)
gaps.sort_values("gap")

,mdr_coverage,xdr_coverage,n_mdr,n_xdr,gap
SOURCE,,,,,
CLIRES2023,0.681,0.758,113.0,62.0,-0.077
NEJM2018,0.892,0.952,1608.0,124.0,-0.060
WHO2019,0.723,0.750,303.0,44.0,-0.027
KMVALIDATION2025,0.965,0.971,1462.0,384.0,-0.006
CLIRES2020,0.729,0.729,188.0,85.0,0.000
CRyPTIC,0.616,0.608,1834.0,561.0,0.008
SEQTREAT2020,0.756,0.212,2201.0,499.0,0.544


In [30]:
# Both pooled figures cover the same isolates, the ones behind the table above.
# Comparing a gap over every isolate against a gap over a subset would fold a
# change of population into what should read as the effect of one exclusion.
compared = pair[pair["SOURCE"].isin(gaps.index)]
worst = gaps["gap"].idxmax()


def tier_gap(frame):
    """MDR coverage less XDR coverage over the isolates given."""
    return (frame.loc[frame["tier"].eq("MDR"), "reachable"].mean()
            - frame.loc[frame["tier"].eq("XDR"), "reachable"].mean())


pd.Series({
    "sources_compared": len(gaps),
    "isolates_compared": len(compared),
    "median_gap": round(float(gaps["gap"].median()), 3),
    "largest_gap": round(float(gaps["gap"].max()), 3),
    "largest_gap_source": worst,
    "pooled_gap": round(float(tier_gap(compared)), 3),
    "pooled_gap_excluding_that_source": round(
        float(tier_gap(compared[compared["SOURCE"].ne(worst)])), 3),
})

sources_compared                               7
isolates_compared                           9468
median_gap                                -0.006
largest_gap                                0.544
largest_gap_source                  SEQTREAT2020
pooled_gap                                 0.174
pooled_gap_excluding_that_source           0.027
dtype: object

### Two renderings of the same catalog
EFFECTS and PREDICTIONS both render the WHO catalog. Across the isolates present in both, the derived profiles agree completely, so the two tables carry the same calls and differ only in which isolates they cover. The coverage gap measured above is the whole of the difference.

That is why the per-drug evaluation and the tier evaluation can draw the catalog arm from different tables without the comparison shifting. The per-drug arm reads EFFECTS, the same grading the rule engine consumes, so drugs outside the class expansion match by construction rather than by agreement. Reading PREDICTIONS instead would move only the gap isolates.

The larger effect is absence rather than disagreement. The count below shows how many isolates carry a measured phenotype with no catalog genotype at all. Those reach scoring with no graded rows and are called susceptible for every drug on both arms, which lowers sensitivity equally on each side and leaves precision untouched, since such an isolate can only become a false negative or a true negative.

In [31]:
effects_call = resistant_profile(DATA / "EFFECTS.parquet", "PREDICTION", drugs)
sources = pd.DataFrame({"effects": effects_call, "predictions": catalog}).dropna()

# Counted against both tables. The engine reads EFFECTS, so that row is the one
# that bounds it; the PREDICTIONS row says whether the choice of table matters.
pd.Series({
    "isolates_in_both": len(sources),
    "profile_agreement": round((sources["effects"] == sources["predictions"]).mean(), 3),
    "labeled_isolates": len(dst),
    "labeled_without_effects": int((~dst.index.isin(effects_call.index)).sum()),
    "labeled_without_predictions": int((~dst.index.isin(catalog.index)).sum()),
})

isolates_in_both               53824.0
profile_agreement                  1.0
labeled_isolates               65588.0
labeled_without_effects        12047.0
labeled_without_predictions    11853.0
dtype: float64

The profile agreement above is measured over isolates. The evaluation arms score
individual drugs, so the sharper question is how far the two tables agree on the
resistant calls themselves. A high share means the rule engine arm and the
catalog arm rest on the same underlying calls and are close to copies of one
another, which is what the scheme note in the per-drug scoring records. Two
arms built this way can agree with each other while both miss the same isolates,
so their agreement is not evidence that either is correct.

In [32]:
def resistance_pairs(path):
    """Isolate and drug pairs the catalog renders as resistant."""
    df = flat(pd.read_parquet(path, columns=["UNIQUEID", "DRUG", "PREDICTION"]), "UNIQUEID")
    return df[df["PREDICTION"].astype(str) == "R"].set_index(["UNIQUEID", "DRUG"]).index


effects_r = resistance_pairs(DATA / "EFFECTS.parquet")
predictions_r = resistance_pairs(DATA / "PREDICTIONS.parquet")
shared = len(effects_r.intersection(predictions_r))

pd.Series({
    "effects_resistant_calls": len(effects_r),
    "predictions_resistant_calls": len(predictions_r),
    "shared_calls": shared,
    "effects_share_also_in_predictions": round(shared / len(effects_r), 3) if len(effects_r) else 0.0,
})

effects_resistant_calls              127866.000
predictions_resistant_calls          120552.000
shared_calls                         119916.000
effects_share_also_in_predictions         0.938
dtype: float64

## 13. WHO catalog grading and gene tier

The graph loader in `who_catalog.py` reads this workbook and writes a resistance edge for every row, with confidence taken from the gene tier. The catalog instead grades each variant for its association with resistance, from group 1 associated with resistance to group 5 not associated. Reading the same sheet shows the grading composition and how little the tier tells us about it, so the loader can be limited to the associated groups and can read confidence from the grading.

In [33]:
# openpyxl warns about a conditional formatting extension this analysis never reads.
warnings.filterwarnings("ignore", message="Conditional Formatting extension")

who = pd.read_excel(DATA / "WHO-UCN-TB-2023.7-eng.xlsx", sheet_name=0, header=2)
gradings = [c for c in who.columns if "grading" in str(c).lower()]
grading = next((c for c in gradings if "final" in str(c).lower()), gradings[0])
who[grading].value_counts(dropna=False)

FINAL CONFIDENCE GRADING
3) Uncertain significance     33906
4) Not assoc w R - Interim    12379
2) Assoc w R - Interim         1130
5) Not assoc w R                484
1) Assoc w R                    253
Name: count, dtype: int64

In [34]:
pd.crosstab(who["tier"], who[grading])

FINAL CONFIDENCE GRADING,1) Assoc w R,2) Assoc w R - Interim,3) Uncertain significance,4) Not assoc w R - Interim,5) Not assoc w R
tier,,,,,
1,253,1130,14958,4998,250
2,0,0,18948,7381,234


## 14. Variant nomenclature on both sides

To merge the catalog mutations with the seed mutations they need one id format. This buckets the catalog variant strings and the CRyPTIC mutation strings by shape, so the canonical token can match what both already use.

Each source writes the same three things, a residue substitution, a base substitution, and a length change. The catalog writes the first two in HGVS and CRyPTIC writes them in a positional shorthand, so the buckets are paired rather than independent. Reading them side by side shows whether the two tables share any notation at all, which decides whether a merge can key on the variant text or has to be rebuilt from gene and position.

In [35]:
# Four shapes in two notations, plus length changes, which both notations write
# the same way. Case carries the level: a lowercase base pair is a nucleotide
# call and an uppercase letter is a residue, which is why rrs variants such as
# a1401g read as nucleotide even though rrs encodes no protein.
SHAPES = ["indel", "protein_hgvs", "nucleotide_hgvs", "nucleotide_short",
          "protein_short"]


def variant_shape(values):
    """Bucket variant strings by nomenclature, first match wins. A trailing
    colon and number is an annotation rather than notation, so it comes off
    first; whatever it records, the variant under it keeps its shape. The
    residue class admits the exclamation mark, which writes a stop codon."""
    text = values.astype(str).str.replace(r":\d+$", "", regex=True)
    tests = [text.str.contains("del|ins|dup|fs", regex=True),
             text.str.contains("p.", regex=False),
             text.str.contains(r"c\.|n\.|>", regex=True),
             text.str.contains(r"^[acgt]-?\d+[acgt]$", regex=True),
             text.str.contains(r"[A-Za-z]\d+[A-Za-z!]", regex=True)]
    return pd.Series(np.select(tests, SHAPES, default="other"), index=values.index)


# Split as the catalog loader splits, so the gene prefix is not classified.
# Locus identifiers carry digits, which put every Rv-numbered LoF row in the
# protein bucket while the same rows on named genes landed in other.
who_variant = (who["variant"].fillna(who["mutation"]).astype(str)
               .str.split("_", n=1).str[-1])
pd.DataFrame({"variant": who_variant, "shape": variant_shape(who_variant)}) \
  .groupby("shape")["variant"].agg(n="size", examples=lambda s: list(s.head(3)))

,n,examples
shape,,
indel,3459,"[c.-81_-76dupTCGGTG, deletion, p.Asp379fs]"
nucleotide_hgvs,20861,"[c.102G>A, c.1044G>A, c.105C>G]"
other,91,"[LoF, LoF, LoF]"
protein_hgvs,23741,"[p.Ala152Val, p.Ala170Thr, p.Ala197Val]"


In [36]:
mutation = flat(pd.read_parquet(DATA / "EFFECTS.parquet", columns=["MUTATION"]),
                "MUTATION")["MUTATION"].astype(str)
pd.DataFrame({"mutation": mutation, "shape": variant_shape(mutation)}) \
  .groupby("shape")["mutation"].agg(n="size", examples=lambda s: list(s.head(3)))

,n,examples
shape,,
indel,15827,"[110_del_a, -38_del_cgttgacggcctcgacattacgttga..."
nucleotide_short,77030,"[c-61t, c-61t, g-10a]"
other,1083,"[a-11x, t-12x, g-37x]"
protein_short,1060187,"[G406A, F320F, A205A]"


## 15. Seed mutations in the catalog nomenclature

Each seed mutation matched to the WHO catalog by gene and position. The candidate column rewrites the protein-coding seeds into three-letter HGVS form. Promoter and ribosomal RNA seeds are not protein coding, so they carry no candidate and merge on the catalog variant text instead. The single-letter amino acid codes overlap the nucleotide bases A, C, G, and T, so the rewrite keys off the HGVS prefix in the seed identifier rather than the residue letters alone.

In [37]:
from who_catalog import WHOCatalog

AA3 = {"A": "Ala", "R": "Arg", "N": "Asn", "D": "Asp", "C": "Cys", "Q": "Gln",
       "E": "Glu", "G": "Gly", "H": "His", "I": "Ile", "L": "Leu", "K": "Lys",
       "M": "Met", "F": "Phe", "P": "Pro", "S": "Ser", "T": "Thr", "W": "Trp",
       "Y": "Tyr", "V": "Val"}

by_gene = dict(tuple(who_variant.groupby(who["gene"].map(WHOCatalog.normalize_gene))))


def protein_hgvs(m):
    """Protein-coding seed rewritten as three-letter HGVS, None for other seeds."""
    ref, alt, pos = m.get("ref"), m.get("alt"), m.get("position")
    if "_p." not in m["id"] or ref not in AA3 or alt not in AA3:
        return None
    return f"{m['gene']}_p.{AA3[ref]}{pos}{AA3[alt]}" if pos > 0 else None


def catalog_matches(gene, position, limit=4):
    """Catalog variants in one gene whose text carries the seed position."""
    variants = by_gene.get(gene)
    if variants is None:
        return []
    return sorted(variants[variants.str.contains(str(position), na=False)].unique())[:limit]


pd.DataFrame([{"seed_id": m["id"],
               "candidate": protein_hgvs(m),
               "who_variants": catalog_matches(m["gene"], m["position"])}
              for m in blobs["mutations"]])

,seed_id,candidate,who_variants
0,rpoB_p.Ser450Leu,rpoB_p.Ser450Leu,"[c.450C>T, p.Ser450Ala, p.Ser450Cys, p.Ser450Gln]"
1,rpoB_p.Asp435Val,rpoB_p.Asp435Val,"[p.Asp435Ala, p.Asp435Asn, p.Asp435Glu, p.Asp4..."
2,rpoB_p.His445Tyr,rpoB_p.His445Tyr,"[p.His445Arg, p.His445Asn, p.His445Asp, p.His4..."
3,rpoB_p.His445Asp,rpoB_p.His445Asp,"[p.His445Arg, p.His445Asn, p.His445Asp, p.His4..."
4,rpoB_p.Leu430Pro,rpoB_p.Leu430Pro,"[c.2430G>C, p.Leu430Arg, p.Leu430Pro, p.Leu430..."
5,katG_p.Ser315Thr,katG_p.Ser315Thr,"[p.Ser315Arg, p.Ser315Asn, p.Ser315Gly, p.Ser3..."
6,katG_p.Ser315Asn,katG_p.Ser315Asn,"[p.Ser315Arg, p.Ser315Asn, p.Ser315Gly, p.Ser3..."
7,katG_p.Ser315Ile,katG_p.Ser315Ile,"[p.Ser315Arg, p.Ser315Asn, p.Ser315Gly, p.Ser3..."
8,inhA_c.-15C>T,None,"[c.-154G>A, c.-156C>T, c.-158C>T, c.-159G>T]"
9,inhA_c.-8T>C,None,"[c.-800_-787delATTTCGGCCCGGCC, c.-801G>A, c.-8..."
